[AIS-36] [AIS-37] - Result page
LUNA-Creatives/ai-summary pull request #9
Opened 2022-10-25 11:33 UTC by olivernygren

2022-10-25 11:52 UTC, boomboxbacardi requested changes

2022-10-25 11:52 UTC, boomboxbacardi commented on ai-summary-front/src/components/result-question/ResultQuestion.tsx
> +  const exampleQuestions = [
`exampleQuestions`

Does not seem to be used anywhere

2022-10-25 11:52 UTC, boomboxbacardi commented on ai-summary-front/src/components/summary-section/SummarySection.tsx
> +            <ResultQuestion question={question} index={index} />
I think this sections hold too much logic about rendering of result questions.

I would rather see rendering of a container e.g. `<StudyQuestions studyQuestions={all_questions_here} />`

Inside `<StudyQuestions />` you shall map the array with questions to render it accordingly

2022-10-25 11:52 UTC, boomboxbacardi commented on ai-summary-front/src/components/summary-section/SummarySection.tsx
> +            <ResultQuestion question={question} index={index} />
Currently, this component is too tightly coupled to another sub component (ResultQuestion) and switching out the component would mean also re-writing the loop.

2022-10-25 11:52 UTC, boomboxbacardi commented on ai-summary-front/src/pages/result/ResultPage.tsx
> +import data from '../../assets/data/pageStrings.json';
`import data` -> `import strings`

2022-10-25 11:52 UTC, boomboxbacardi commented on ai-summary-front/src/components/result-question/ResultQuestion.tsx
> +          {index + 1}
If you do it like this, it means that this component is tightly coupled to a specific feature (e.g numbering in a list). The component is too smart! And should be much less smart :) 

It is not the job of this to calculate the value of the numbering index. It should just render whatever data is passed into the props.

2022-10-25 11:55 UTC, olivernygren commented on ai-summary-front/src/components/result-question/ResultQuestion.tsx
> +  const exampleQuestions = [
This has been removed

2022-10-25 13:40 UTC, boomboxbacardi requested changes

2022-10-25 13:40 UTC, boomboxbacardi commented on ai-summary-front/src/pages/result/ResultPage.tsx
> +        <SummarySection type="questions" />
I think `<SummarySection` hold too much logic since it's the decider whether to show text or questions.

Its tightly coupled to the layour for text and questions. What would happen if we where to add another summary section with answers instead?
Then, we would've added another `<SummarySection type="answers">` and another section heading if-statement, another conditional rendering etc..

Perhaps the sections should be "dumber" and just render whatever passes to them?

A suggestion would be refactoring and adding:

`<TextSummarySection text={some_text}  /> // Renders whatever text is passed here` 
`<BulletpointSummarySection someTextArray={some_questions_in_an_array} />`

2022-10-26 07:13 UTC, boomboxbacardi approved these changes
Nice!

2022-10-26 07:28 UTC, merged